version: '3'
services:
  ########################################
  about_customer_front:
    container_name: about_customer_front_con
    image: pavi03/clonet_about_customer_front
    ports:
      - 8001:80
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-1
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: about_customer_front

  about_customer_back:
    container_name: about_customer_back_con
    image: pavi03/clonet_about_customer_back
    ports:
      - 8081:8081
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-2
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: about_customer_back
  # ########################################
  home_front:
    container_name: home_front_con
    image: pavi03/clonet_home_front
    ports:
      - 8005:80
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-3
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: home_front

  home_back:
    container_name: home_back_con
    image: pavi03/clonet_home_back
    ports:
      - 8085:8085
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-4
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: home_back
  #######################################
  illust_customer_front:
    container_name: illust_customer_front_con
    image: pavi03/clonet_illust_customer_front
    ports:
     - 8006:80
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-5
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: illust_customer_front

  illust_customer_back:
    container_name: illust_customer_back_con
    image: pavi03/clonet_illust_customer_back
    ports:
     - 8086:8086
    depends_on :
     - kafka
     - zookeeper
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-6
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: illust_customer_back
  ########################################
  illust_select_user_front:
    container_name: illust_select_user_front_con
    image: pavi03/clonet_illust_select_user_front
    ports:
      - 8007:80
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-7
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: illust_select_user_front

  illust_select_user_back:
    container_name: illust_select_user_back_con
    image: pavi03/clonet_illust_select_user_back
    ports:
      - 8087:8087
    depends_on:
      - kafka
      - zookeeper
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-8
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: illust_select_user_back
  ########################################

  #######################################
  zookeeper:
    container_name: zookeeper_con
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-9
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: zookeeper


  kafka:
    container_name: kafka_con
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.44
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-cluster-10
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: kafka

########################################