version: '3'
services:
  about_customer:
    build:
      context: .
      dockerfile: ./About_Customer/Dockerfile
    container_name: about_customer_con
    volumes:
      - ./About_Customer:/app
    ports:
      - 2000:2000
    networks:
      - clonet_network

  about_edit_user:
    build:
      context: .
      dockerfile: ./About_Edit_User/Dockerfile
    container_name: about_edit_user_con
    volumes:
      - ./About_Edit_User:/app
    ports:
      - 2001:2001
    networks:
      - clonet_network

  contact_customer:
    build:
      context: .
      dockerfile: ./Contact_Customer/Dockerfile
    container_name: contact_customer_con
    volumes:
      - ./Contact_Customer:/app
    ports:
      - 2002:2002
    networks:
      - clonet_network

  contact_edit_user:
    build:
      context: .
      dockerfile: ./Contact_Edit_User/Dockerfile
    container_name: contact_edit_user_con
    volumes:
      - ./Contact_Edit_User:/app
    ports:
      - 2003:2003
    networks:
      - clonet_network

  home:
    build:
      context: .
      dockerfile: ./Home/Dockerfile
    container_name: home_con
    volumes:
      - ./Home:/app
    ports:
      - 2004:2004
    networks:
      - clonet_network

  illust_customer:
    build:
      context: .
      dockerfile: ./Illust_Customer/Dockerfile
    container_name: illust_customer_con
    volumes:
      - ./Illust_Customer:/app
    ports:
      - 2005:2005
    networks:
      - clonet_network

  illust_select_user:
    build:
      context: .
      dockerfile: ./Illust_Select_User/Dockerfile
    container_name: illust_select_user_con
    volumes:
      - ./Illust_Select_User:/app
    ports:
      - 2006:2006
    networks:
      - clonet_network

  login:
    build:
      context: .
      dockerfile: ./Login/Dockerfile
    container_name: login_con
    volumes:
      - ./Login:/app
    ports:
      - 2007:2007
    networks:
      - clonet_network


networks:
  clonet_network:
    external: true
