version: '3'

services:
  home:
    build:
      context: .
      dockerfile: ./Home/Dockerfile
      args:
        JAR_FILE: ./Home/build/libs/*.jar
    container_name: home_con
    volumes:
      - ./Home:/app
    ports:
      - 8080:8080
    networks:
      - clonet_network
    restart: always

networks:
  clonet_network:
    external: true
