management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  datasource:
    url: jdbc:mysql://{}}/clonet_database?characterEncoding=utf8&useSSL=false
    username: admin
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**.xml